name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-server --version"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -e ".[test]"

      - name: Wait for Redis to be ready
        run: |
          python - <<'PY'
          import time, socket, sys

          for _ in range(20):
              try:
                  with socket.create_connection(("localhost", 6379), timeout=1):
                      print("Redis is up")
                      sys.exit(0)
              except OSError:
                  print("Waiting for Redis...")
                  time.sleep(1)

          raise RuntimeError("Redis not reachable")
          PY

      - name: Run tests
        run: pytest -v tests